get enUS => {
      // Global names
      'app_name': 'Inkubox App',
      'menu_home': 'Home',
      'menu_calculator': 'Calculator',
      'change_theme_button': 'Change Theme',
      'admin_pannel_button': 'Admin pannel',
      'edit_profile_button': 'Edit Profile',
      'error_title': 'Error',
      'info_title': 'Information',
      'message_title': 'Message',
      // Login View
      'login_title': 'Login',
      'login_email': 'Email',
      'login_password': 'Password',
      'login_button': 'Login',
      'login_reset_password': 'Reset password',
      'logout_not_connected': 'Not connected!',
      'logout_button': 'Logout',
      // Sign-Up view
      'sign_up_title': 'Sign Up',
      'sign_up_error_email_field': 'Enter valid e-mail address.',
      'sign_up_label_email': 'E-mail',
      'sign_uo_label_display_name': 'Display Name',
      'sign_up_error_display_name_field': 'Display Name is required.',
      'sign_up_label_password': 'Password',
      'sign_up_error_password_field': 'Password is required.',
      'sign_up_label_confirm_password': 'Confirm password',
      'sign_up_error_confirm_password_field': 'Passwords do not match.',
      'sign_up_button': 'Sign Up',
      // Profile view
      'profile_email': 'Email',
      'profile_display_name': 'Display name',
      'profile_position': 'Position',
      'profile_phone': 'Phone',
      'profile_info_text': '* Edited data is saved automatically.',
      'profile_password': 'Password',
      'profile_new_password': 'New password',
      'profile_new_password_required': 'Password is required.',
      'profile_confirm_password': 'Confirm password',
      'profile_passwords_not_match': 'Passwords do not match.',
      'profile_change_password_button': 'Change password',
      // Calculator view
      'calculator_sum_usd': 'Sum (USD):',
      'calculatoe_sum_usd_hint': 'Enter Amount in USD and press ENTER',
      'calculator_sum_usd_undertext': '* Enter sum in USD and press ENTER',
      'calculator_calculated_sum_eur': 'Calculated sum (EUR):',
      'calculator_calculated_sum_eur_hint': 'Sum in EUR',
      'calculator_eur_to_usd_rate': 'Current USD to EUR rate:',
      'calculator_eur_to_usd_rate_hint': '1 USD in EUR',
      // Admin dashboard view
      'admin_dashboard_title': "Administrator's Dashboard",
      'admin_dashboard_manage_users': 'Manage users',
      'admin_dashboard_all_calculations': 'Review all calculations',
      // All calculations view
      'all_calculations_filters_title': 'Filters',
      'all_calculations_filter_initial_sum': 'Initial sum',
      'all_calculations_filter_greater_than': 'greater than',
      'all_calculations_filter_equals': 'equals',
      'all_calculations_filter_less_than': 'less than',
      'all_calculations_filter_clear_button': 'Clear',
      'all_calculations_filter_refresh_button': 'Refresh',
      'all_calculations_column_email': 'E-mail',
      'all_calculations_column_operation_time': 'Operation time',
      'all_calculations_column_initial_sum': 'Initial sum',
      'all_calculations_column_calculated_sum': 'Calculated sum',
      'all_calculations_column_rate': 'EUR to USD rate',
      // All users view
      'all_users_info_access_mode': "User's access mode was changed",
      // Authorize user
      'auth_validate_email_mandatory': 'E-mail must be provided.',
      'auth_validate_email_invalid': 'Not valid e-mail.',
      'auth_validate_password_mandatory': 'Password must be provided.',
      'auth_validate_passwords_unmatch': 'Passwords do not match.',
      'auth_error_weak_password': 'The password provided is too weak!',
      'auth_error_email-already-in-use':
          'The account already exists for that email.',
      'auth_error_not_loggedin': 'You are not loggedin!',
      'auth_error_user-mismatch':
          'The credential given does not correspond to the user.',
      'auth_error_user-not-found':
          'The credential given does not correspond to the user.',
      'auth_error_invalid-credential':
          'The provider' 's credential is not valid.',
      'auth_error_invalid-email': "The provider's email is not valid.",
      'auth_error_wrong-password': 'The provided password is not valid.',
      'aut_error_authentication_error': 'Authentication error!',
      'auth_error_password_check_error': 'Password check error!',
      'auth_message_enter_credentials': 'Enter email and password.',
      'auth_message_password_changed': 'Password successfully changed.',
      'auth_reset_password_question':
          'Do You really want to reset your password?',
      // Profile change
      'profile_change_display_name_updated': 'Display name was updated.',
      'profile_change_possition_updated': 'Possition was updated.',
      'profile_change_phone_updated': 'Phone was updated.',
      'profile_change_enabled_changed':
          "User's account access right was changed.",
      'profile_change_password_empty': 'The password is empty!',
      'profile_change_unimplemented_feature':
          'Sorry! Feature is not implemented yet.',
    };
