get enUS => {
      'app_name': 'Inkubox App',
      'menu_home': 'Home',
      'menu_calculator': 'Calculator',
      'change_theme_button': 'Change Theme',
      'login_email': 'Email',
      'login_password': 'Password',
      'login_button': 'Login',
      'logout_not_connected': 'Not connected!',
      'logout_button': 'Logout',
      'sign_up_title': 'Sign Up',
      'sign_up_error_email_field': 'Enter valid e-mail address.',
      'sign_up_label_email': 'E-mail',
      'sign_uo_label_display_name': 'Display Name',
      'sign_up_error_display_name_field': 'Display Name is required.',
      'sign_up_label_password': 'Password',
      'sign_up_error_password_field': 'Password is required.',
      'sign_up_label_confirm_password': 'Confirm password',
      'sign_up_error_confirm_password_field': 'Passwords do not match.',
      'sign_up_button': 'Sign Up',
      'admin_pannel_button': 'Admin pannel',
      'edit_profile_button': 'Edit Profile',
    };
