get frFR => {
      'app_name': 'Inkubox App-fr',
      'menu_home': 'Home-fr',
      'menu_calculator': 'Calculator-fr',
      'change_theme_button': 'Change Theme-fr',
      'login_email': 'Email-fr',
      'login_password': 'Password-fr',
      'login_button': 'Login-fr',
      'logout_not_connected': 'Not connected!-fr',
      'logout_button': 'Logout-fr',
      'sign_up_title': 'Sign Up-fr',
      'sign_up_error_email_field': 'Enter valid e-mail address.-fr',
      'sign_up_label_email': 'E-mail-fr',
      'sign_uo_label_display_name': 'Display Name-fr',
      'sign_up_error_display_name_field': 'Display Name is required.-fr',
      'sign_up_label_password': 'Password-fr',
      'sign_up_error_password_field': 'Password is required.-fr',
      'sign_up_label_confirm_password': 'Confirm password-fr',
      'sign_up_error_confirm_password_field': 'Passwords do not match.-fr',
      'sign_up_button': 'Sign Up-fr',
      'admin_pannel_button': 'Admin pannel-fr',
      'edit_profile_button': 'Edit Profile-fr',
    };
