get frFR => {
      // Global names
      'app_name': 'Inkubox App-fr',
      'menu_home': 'Home-fr',
      'menu_calculator': 'Calculator-fr',
      'change_theme_button': 'Change Theme-fr',
      'admin_pannel_button': 'Admin pannel-fr',
      'edit_profile_button': 'Edit Profile-fr',
      'error_title': 'Error-fr',
      'info_title': 'Information-fr',
      'message_title': 'Message-fr',
      // Login View
      'login_title': 'Login-fr',
      'login_email': 'Email-fr',
      'login_password': 'Password-fr',
      'login_button': 'Login-fr',
      'login_reset_password': 'Reset password-fr',
      'logout_not_connected': 'Not connected!-fr',
      'logout_button': 'Logout-fr',
      // Sign-Up Wiew
      'sign_up_title': 'Sign Up-fr',
      'sign_up_error_email_field': 'Enter valid e-mail address.-fr',
      'sign_up_label_email': 'E-mail-fr',
      'sign_uo_label_display_name': 'Display Name-fr',
      'sign_up_error_display_name_field': 'Display Name is required.-fr',
      'sign_up_label_password': 'Password-fr',
      'sign_up_error_password_field': 'Password is required.-fr',
      'sign_up_label_confirm_password': 'Confirm password-fr',
      'sign_up_error_confirm_password_field': 'Passwords do not match.-fr',
      'sign_up_button': 'Sign Up-fr',
      // Profile view
      'profile_email': 'Email-fr',
      'profile_display_name': 'Display name-fr',
      'profile_position': 'Position-fr',
      'profile_phone': 'Phone-fr',
      'profile_info_text': '* Edited data is saved automatically.-fr',
      'profile_password': 'Password-fr',
      'profile_new_password': 'New password-fr',
      'profile_new_password_required': 'Password is required.-fr',
      'profile_confirm_password': 'Confirm password-fr',
      'profile_passwords_not_match': 'Passwords do not match.-fr',
      'profile_change_password_button': 'Change password-fr',
      // Calculator view
      'calculator_sum_usd': 'Sum (USD):-fr',
      'calculatoe_sum_usd_hint': 'Enter Amount in USD and press ENTER-fr',
      'calculator_sum_usd_undertext': '* Enter sum in USD and press ENTER-fr',
      'calculator_calculated_sum_eur': 'Calculated sum (EUR):-fr',
      'calculator_calculated_sum_eur_hint': 'Sum in EUR-fr',
      'calculator_eur_to_usd_rate': 'Current USD to EUR rate:-fr',
      'calculator_eur_to_usd_rate_hint': '1 USD in EUR-fr',
      // Admin dashboard view
      'admin_dashboard_title': "Administrator's Dashboard-fr",
      'admin_dashboard_manage_users': 'Manage users-fr',
      'admin_dashboard_all_calculations': 'Review all calculations-fr',
      // All calculations view
      'all_calculations_filters_title': 'Filters-fr',
      'all_calculations_filter_initial_sum': 'Initial sum-fr',
      'all_calculations_filter_greater_than': 'greater than-fr',
      'all_calculations_filter_equals': 'equals-fr',
      'all_calculations_filter_less_than': 'less than-fr',
      'all_calculations_filter_clear_button': 'Clear-fr',
      'all_calculations_filter_refresh_button': 'Refresh-fr',
      'all_calculations_column_email': 'E-mail-fr',
      'all_calculations_column_operation_time': 'Operation time-fr',
      'all_calculations_column_initial_sum': 'Initial sum-fr',
      'all_calculations_column_calculated_sum': 'Calculated sum-fr',
      'all_calculations_column_rate': 'EUR to USD rate-fr',
      // All users view
      'all_users_info_access_mode': "User's access mode was changed-fr",
      // Authorize user
      'auth_validate_email_mandatory': 'E-mail must be provided.-fr',
      'auth_validate_email_invalid': 'Not valid e-mail.-fr',
      'auth_validate_password_mandatory': 'Password must be provided.-fr',
      'auth_validate_passwords_unmatch': 'Passwords do not match.-fr',
      'auth_error_weak_password': 'The password provided is too weak!-fr',
      'auth_error_email-already-in-use':
          'The account already exists for that email.-fr',
      'auth_error_not_loggedin': 'You are not loggedin!-fr',
      'auth_error_user-mismatch':
          'The credential given does not correspond to the user.-fr',
      'auth_error_user-not-found':
          'The credential given does not correspond to the user.-fr',
      'auth_error_invalid-credential':
          'The provider' 's credential is not valid.-fr',
      'auth_error_invalid-email': "The provider's email is not valid.-fr",
      'auth_error_wrong-password': 'The provided password is not valid.-fr',
      'aut_error_authentication_error': 'Authentication error!-fr',
      'auth_error_password_check_error': 'Password check error!-fr',
      'auth_message_enter_credentials': 'Enter email and password.-fr',
      'auth_message_password_changed': 'Password successfully changed.-fr',
      'auth_reset_password_question':
          'Do You really want to reset your password?-fr',
      // Profile change
      'profile_change_display_name_updated': 'Display name was updated.-fr',
      'profile_change_possition_updated': 'Possition was updated.-fr',
      'profile_change_phone_updated': 'Phone was updated.-fr',
      'profile_change_enabled_changed':
          "User's account access right was changed.-fr",
      'profile_change_password_empty': 'The password is empty!-fr',
      'profile_change_unimplemented_feature':
          'Sorry! Feature is not implemented yet.-fr',
    };
