get ltLT => {
      // Bendri pavadinimai
      'app_name': 'Pinigų skaičiuotuvas',
      'menu_home': 'Pradžia',
      'menu_calculator': 'Skaičiuoklė',
      'change_theme_button': 'Keisti temą',
      'admin_pannel_button': 'Administruoti',
      'edit_profile_button': 'Mano profilis',
      'error_title': 'Klaida',
      'info_title': 'Informacija',
      'message_title': 'Pranešimas',
      // Prisijungimo vaizdas
      'login_title': 'Prisijungti',
      'login_email': 'El.paštas',
      'login_password': 'Slaptažodis',
      'login_button': 'Jungtis',
      'login_reset_password': 'Atnaujinti slaptažodį',
      'logout_not_connected': 'Neprisijungta!',
      'logout_button': 'Atsijungti',
      // Registravimosi vaizdas
      'sign_up_title': 'Registruotis',
      'sign_up_error_email_field': 'Įrašykite teisingą el.pašto adresą.',
      'sign_up_label_email': 'El.paštas',
      'sign_uo_label_display_name': 'Vardas',
      'sign_up_error_display_name_field': 'Vardas yra būtinas.',
      'sign_up_label_password': 'Slaptažodis',
      'sign_up_error_password_field': 'Slaptažodis yra būtinas.',
      'sign_up_label_confirm_password': 'Pakartokite slaptažodį',
      'sign_up_error_confirm_password_field': 'Slaptažodžiai nesutampa.',
      'sign_up_button': 'Registruotis',
      // Profile view
      'profile_email': 'El.paštas',
      'profile_display_name': 'Vardas',
      'profile_position': 'Pareigybės',
      'profile_phone': 'Telefonas',
      'profile_info_text': '* Koreguoti duomenys išsaugomi automatiškai.',
      'profile_password': 'Slaptažodis',
      'profile_new_password': 'Naujas slaptažodis',
      'profile_new_password_required': 'Slaptažodis yra būtinas.',
      'profile_confirm_password': 'Patvirtinkite slaptažodį',
      'profile_passwords_not_match': 'Slaptažodžiai nesutampa.',
      'profile_change_password_button': 'Pakeisti slaptažodį',
      // Calculator view
      'calculator_sum_usd': 'Suma (USD):',
      'calculatoe_sum_usd_hint': 'Įveskite sumą USD ir spauskite ENTER',
      'calculator_sum_usd_undertext': '* Įveskite sumą USD ir spauskite ENTER',
      'calculator_calculated_sum_eur': 'Apskaičiuota suma (EUR):',
      'calculator_calculated_sum_eur_hint': 'Suma EUR',
      'calculator_eur_to_usd_rate': 'Dabartinis USD ir EUR santykis:',
      'calculator_eur_to_usd_rate_hint': '1 USD vertė EUR',
      // Admin dashboard view
      'admin_dashboard_title': "Administratoriaus valdymo skydelis",
      'admin_dashboard_manage_users': 'Valdyti vartotojus',
      'admin_dashboard_all_calculations': 'Peržiūrėti visus paskaičiavimus',
      // All calculations view
      'all_calculations_filters_title': 'Filtrai',
      'all_calculations_filter_initial_sum': 'Pradinė suma',
      'all_calculations_filter_greater_than': 'daugiau nei',
      'all_calculations_filter_equals': 'lygi',
      'all_calculations_filter_less_than': 'mažiau nei',
      'all_calculations_filter_clear_button': 'Išvalyti',
      'all_calculations_filter_refresh_button': 'Naujinti',
      'all_calculations_column_email': 'El.paštas',
      'all_calculations_column_operation_time': 'Operacijos laikas',
      'all_calculations_column_initial_sum': 'Pradinė suma',
      'all_calculations_column_calculated_sum': 'Suskaičiuota suma',
      'all_calculations_column_rate': 'EUR su USD kursas',
      // All users view
      'all_users_info_access_mode': "Vartotojo priėjimo teisės pakeistos",
      // Authorize user
      'auth_validate_email_mandatory': 'El.paštas yra būtinas.',
      'auth_validate_email_invalid': 'Neteisingas el.pašto formatas.',
      'auth_validate_password_mandatory': 'Slaptažodis yra būtinas.',
      'auth_validate_passwords_unmatch': 'Slaptažodžiai nesutampa.',
      'auth_error_weak_password': 'Pateiktas slaptažodis yra per silpnas!',
      'auth_error_email-already-in-use':
          'Vartotojas su tokiu el.paštu jau egzistuoja.',
      'auth_error_not_loggedin': 'Jūs neprisijungęs!',
      'auth_error_user-mismatch': 'Pateikti duomenys nepriklauso vartotojui.',
      'auth_error_user-not-found': 'Pateikti duomenys nepriklauso vartotojui.',
      'auth_error_invalid-credential': 'Pateikti duomenys yra netikslūs.',
      'auth_error_invalid-email': 'Pateikėjo el.paštas neatitinka.',
      'auth_error_wrong-password': 'Pateiktas slaptažodis neatitinka.',
      'aut_error_authentication_error': 'Autentifikavimo klaida!',
      'auth_error_password_check_error': 'Slaptažodžio tikrinimo klaida!',
      'auth_message_enter_credentials': 'Įveskite el.paštą ir slaptažodį.',
      'auth_message_password_changed': 'Slaptažodis sėkmingai pakeistas.',
      'auth_reset_password_question':
          'Ar jūs tikrai norite atstatyti slaptažodį?',
      // Profile change
      'profile_change_display_name_updated': 'Vartotojo vardas buvo pakeistas.',
      'profile_change_possition_updated': 'Pareigos buvo pakeistos.',
      'profile_change_phone_updated': 'Telefonas buvo pakeistas.',
      'profile_change_enabled_changed':
          "Vartotojo prisijungimo teisės buvo pakeistos.",
      'profile_change_password_empty': 'Tuščias slaptažodis!',
      'profile_change_unimplemented_feature':
          'Atsiprašome! Šios galimybės dar nėra.',
    };
