get ltLT => {
      'app_name': 'Pinigų skaičiuotuvas',
      'menu_home': 'Pradžia',
      'menu_calculator': 'Skaičiuoklė',
      'change_theme_button': 'Keisti temą',
      'login_email': 'El.paštas',
      'login_password': 'Slaptažodis',
      'login_button': 'Jungtis',
      'logout_not_connected': 'Neprisijungta!',
      'logout_button': 'Atsijungti',
      'sign_up_title': 'Registruotis',
      'sign_up_error_email_field': 'Įrašykite teisingą el.pašto adresą.',
      'sign_up_label_email': 'El.paštas',
      'sign_uo_label_display_name': 'Vardas',
      'sign_up_error_display_name_field': 'Vardas yra būtinas.',
      'sign_up_label_password': 'Slaptažodis',
      'sign_up_error_password_field': 'Slaptažodis yra būtinas.',
      'sign_up_label_confirm_password': 'Pakartokite slaptažodį',
      'sign_up_error_confirm_password_field': 'Slaptažodžiai nesutampa.',
      'sign_up_button': 'Registruotis',
      'admin_pannel_button': 'Administruoti',
      'edit_profile_button': 'Mano profilis',
    };
