get ltLT => {
      // Bendri pavadinimai
      'app_name': 'Pinigų skaičiuotuvas',
      'menu_home': 'Pradžia',
      'menu_calculator': 'Skaičiuoklė',
      'change_theme_button': 'Keisti temą',
      'admin_pannel_button': 'Administruoti',
      'edit_profile_button': 'Mano profilis',
      'error_title': 'Klaida',
      'info_title': 'Informacija',
      'message_title': 'Pranešimas',
      // Prisijungimo vaizdas
      'login_title': 'Prisijungti',
      'login_email': 'El.paštas',
      'login_password': 'Slaptažodis',
      'login_button': 'Jungtis',
      'login_reset_password': 'Atnaujinti slaptažodį',
      'logout_not_connected': 'Neprisijungta!',
      'logout_button': 'Atsijungti',
      // Registravimosi vaizdas
      'sign_up_title': 'Registruotis',
      'sign_up_error_email_field': 'Įrašykite teisingą el.pašto adresą.',
      'sign_up_label_email': 'El.paštas',
      'sign_uo_label_display_name': 'Vardas',
      'sign_up_error_display_name_field': 'Vardas yra būtinas.',
      'sign_up_label_password': 'Slaptažodis',
      'sign_up_error_password_field': 'Slaptažodis yra būtinas.',
      'sign_up_label_confirm_password': 'Pakartokite slaptažodį',
      'sign_up_error_confirm_password_field': 'Slaptažodžiai nesutampa.',
      'sign_up_button': 'Registruotis',
      // Profile view
      'profile_email': 'El.paštas',
      'profile_display_name': 'Vardas',
      'profile_position': 'Pareigybės',
      'profile_phone': 'Telefonas',
      'profile_info_text': '* Koreguoti duomenys išsaugomi automatiškai.',
      'profile_password': 'Slaptažodis',
      'profile_new_password': 'Naujas slaptažodis',
      'profile_new_password_required': 'Slaptažodis yra būtinas.',
      'profile_confirm_password': 'Patvirtinkite slaptažodį',
      'profile_passwords_not_match': 'Slaptažodžiai nesutampa.',
      'profile_change_password_button': 'Pakeisti slaptažodį',
      // Calculator view
      'calculator_sum_usd': 'Suma (USD):',
      'calculatoe_sum_usd_hint': 'Įveskite sumą USD ir spauskite ENTER',
      'calculator_sum_usd_undertext': '* Įveskite sumą USD ir spauskite ENTER',
      'calculator_calculated_sum_eur': 'Apskaičiuota suma (EUR):',
      'calculator_calculated_sum_eur_hint': 'Suma EUR',
      'calculator_eur_to_usd_rate': 'Dabartinis USD ir EUR santykis:',
      'calculator_eur_to_usd_rate_hint': '1 USD vertė EUR',
      // Admin dashboard view
      'admin_dashboard_title': "Administratoriaus valdymo skydelis",
      'admin_dashboard_manage_users': 'Valdyti vartotojus',
      'admin_dashboard_all_calculations': 'Peržiūrėti visus paskaičiavimus',
      // All calculations view
      'all_calculations_silters_title': 'Filtrai',
      'all_calculations_filter_initial_sum': 'Pradinė suma',
      'all_calculations_filter_greater_than': 'daugiau nei',
      'all_calculations_filter_equals': 'lygi',
      'all_calculations_filter_less_than': 'mažiau nei',
      'all_calculations_filter_clear_button': 'Išvalyti',
      'all_calculations_filter_refresh_button': 'Naujinti',
      'all_calculations_column_email': 'El.paštas',
      'all_calculations_column_operation_time': 'Operacijos laikas',
      'all_calculations_column_initial_sum': 'Pradinė suma',
      'all_calculations_column_calculated_sum': 'Suskaičiuota suma',
      'all_calculations_column_rate': 'EUR su USD kursas',
    };
